{% set name = "planetary-computer" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/planetary-computer-{{ version }}.tar.gz
  sha256: 95a76d18337a4dbeaa8919e71a433053398998a5e6f88e106f4c245849935b50

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - planetarycomputer = planetary_computer.scripts.cli:app

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - click >=7.1
    - pydantic >=1.7.3
    - pystac >=1.0.0
    - pystac-client >=0.2.0
    - python >=3.7
    - pytz >=2020.5
    - requests >=2.25.1

test:
  imports:
    - planetary_computer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/planetary-computer/
  summary: Planetary Computer SDK for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - TomAugspurger
    - lossyrob
